export type OutputId =
  | "linkedin"
  | "twitter"
  | "advisory"
  | "infographic"
  | "execsummary"
  | "presentation"
  | "report"
  | "video";

export type GenParams = {
  audience: string;
  tone: string;
  language: string;
  detail: string;
  objective: string;
};

export type SourceFileMeta = {
  name: string;
  size: number;
  type: string;
  extracted: boolean;
  note: string;
};

export type SourceAnalysis = {
  characters: number;
  words: number;
  readingMinutes: number;
  files: SourceFileMeta[];
  limitations: string[];
  supported: string[];
  unsupported: string[];
};

export type Shot = {
  scene: string;
  start: number;
  end: number;
  visual: string;
  narration: string;
  onscreen: string;
};

export type Artifacts = {
  linkedin?: { text: string; hashtags: string[] };
  twitter?: { posts: string[] };
  advisory?: {
    classification: string;
    distribution: string;
    reference: string;
    subject: string;
    sections: { heading: string; body: string }[];
  };
  infographic?: {
    title: string;
    subtitle: string;
    stats: { value: string; label: string }[];
    points: string[];
    footer: string;
  };
  execsummary?: { title: string; bullets: string[]; body: string };
  presentation?: { slides: { title: string; bullets: string[]; notes: string }[] };
  report?: { title: string; sections: { heading: string; body: string }[] };
  video?: {
    logline: string;
    runtimeSeconds: number;
    shots: Shot[];
    visualDirection: string;
    productionNotes: string;
  };
};

export const OUTPUT_TYPES: { id: OutputId; icon: string; name: string; desc: string }[] = [
  {
    id: "linkedin",
    icon: "in",
    name: "LinkedIn Post",
    desc: "Government-style professional post with hashtags",
  },
  {
    id: "twitter",
    icon: "X",
    name: "X / Twitter Thread",
    desc: "Sequenced posts, each under 280 characters",
  },
  {
    id: "advisory",
    icon: "AD",
    name: "Formal Advisory",
    desc: "Structured advisory with classification placeholders",
  },
  {
    id: "infographic",
    icon: "IG",
    name: "Infographic",
    desc: "Design brief plus a rendered downloadable visual",
  },
  {
    id: "execsummary",
    icon: "ES",
    name: "Executive Summary",
    desc: "Concise decision-ready briefing",
  },
  {
    id: "presentation",
    icon: "PR",
    name: "Presentation Outline",
    desc: "Slide-by-slide deck with speaker notes",
  },
  { id: "report", icon: "RP", name: "Report / Article", desc: "Long-form written report" },
  {
    id: "video",
    icon: "VP",
    name: "Video Production Package",
    desc: "Storyboard, shot list, narration, SRT subtitles",
  },
];

export const DRAFT_NOTICE =
  "DRAFT — NOT FOR RELEASE. Generated by GenNexus from user-supplied source material. Requires review and approval by an authorized officer before any internal or public distribution. GenNexus is an independent drafting tool and is not affiliated with, endorsed by, or operated by NTRO or any government agency.";

function pad(n: number, len = 2) {
  return String(Math.floor(n)).padStart(len, "0");
}

export function srtTime(seconds: number) {
  const ms = Math.round((seconds - Math.floor(seconds)) * 1000);
  const s = Math.floor(seconds);
  return `${pad(s / 3600)}:${pad((s % 3600) / 60)}:${pad(s % 60)},${pad(ms, 3)}`;
}

export function buildSrt(shots: Shot[]): string {
  return shots
    .filter((s) => (s.narration || s.onscreen || "").trim().length > 0)
    .map((s, i) => {
      const start = Number.isFinite(s.start) ? s.start : i * 5;
      const end = Number.isFinite(s.end) && s.end > start ? s.end : start + 5;
      const text = (s.narration || s.onscreen).trim();
      return `${i + 1}\n${srtTime(start)} --> ${srtTime(end)}\n${text}\n`;
    })
    .join("\n");
}

export function infographicSvg(ig: NonNullable<Artifacts["infographic"]>): string {
  const esc = (t: string) =>
    String(t).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const wrap = (text: string, max: number) => {
    const words = String(text).split(/\s+/);
    const lines: string[] = [];
    let cur = "";
    for (const w of words) {
      if ((cur + " " + w).trim().length > max) {
        lines.push(cur.trim());
        cur = w;
      } else cur += " " + w;
    }
    if (cur.trim()) lines.push(cur.trim());
    return lines;
  };

  const stats = ig.stats.slice(0, 3);
  const statBlocks = stats
    .map((s, i) => {
      const x = 80 + i * 320;
      return `<g><rect x="${x}" y="300" width="280" height="150" rx="4" fill="#131A22" stroke="#2E3B49"/>
      <text x="${x + 24}" y="368" font-family="Georgia, serif" font-size="44" fill="#FF9F45" font-weight="700">${esc(s.value)}</text>
      ${wrap(s.label, 26)
        .slice(0, 2)
        .map(
          (l, li) =>
            `<text x="${x + 24}" y="${400 + li * 22}" font-family="Helvetica, sans-serif" font-size="15" fill="#8FA0B3">${esc(l)}</text>`,
        )
        .join("")}</g>`;
    })
    .join("");

  let y = 500;
  const pointBlocks = ig.points
    .slice(0, 5)
    .map((p) => {
      const lines = wrap(p, 78).slice(0, 2);
      const block = `<circle cx="90" cy="${y - 6}" r="5" fill="#3FAE72"/>${lines
        .map(
          (l, li) =>
            `<text x="112" y="${y + li * 26}" font-family="Helvetica, sans-serif" font-size="18" fill="#E7ECF2">${esc(l)}</text>`,
        )
        .join("")}`;
      y += 26 * lines.length + 22;
      return block;
    })
    .join("");

  const titleLines = wrap(ig.title, 40).slice(0, 2);

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="${Math.max(880, y + 140)}" viewBox="0 0 1080 ${Math.max(880, y + 140)}">
  <rect width="100%" height="100%" fill="#0A0E13"/>
  <rect x="0" y="0" width="1080" height="8" fill="#FF9F45"/>
  <text x="80" y="110" font-family="Courier New, monospace" font-size="16" fill="#8FA0B3" letter-spacing="3">GENNEXUS // DRAFT — NOT FOR RELEASE</text>
  ${titleLines
    .map(
      (l, i) =>
        `<text x="80" y="${180 + i * 56}" font-family="Georgia, serif" font-size="48" fill="#E7ECF2" font-weight="700">${esc(l)}</text>`,
    )
    .join("")}
  ${wrap(ig.subtitle, 70)
    .slice(0, 2)
    .map(
      (l, i) =>
        `<text x="80" y="${190 + titleLines.length * 56 + i * 26}" font-family="Helvetica, sans-serif" font-size="19" fill="#8FA0B3">${esc(l)}</text>`,
    )
    .join("")}
  ${statBlocks}
  ${pointBlocks}
  <line x1="80" y1="${y + 20}" x2="1000" y2="${y + 20}" stroke="#212B36"/>
  <text x="80" y="${y + 56}" font-family="Courier New, monospace" font-size="14" fill="#5B6B7D">${esc(ig.footer).slice(0, 110)}</text>
  <text x="80" y="${y + 80}" font-family="Courier New, monospace" font-size="13" fill="#5B6B7D">Unreviewed draft — authorized review required before distribution.</text>
</svg>`;
}

export function artifactToText(id: OutputId, a: Artifacts): string {
  const head = `${DRAFT_NOTICE}\n\n${"=".repeat(70)}\n\n`;
  switch (id) {
    case "linkedin": {
      const d = a.linkedin;
      if (!d) return "";
      return head + d.text + "\n\n" + d.hashtags.map((h) => (h.startsWith("#") ? h : "#" + h)).join(" ");
    }
    case "twitter": {
      const d = a.twitter;
      if (!d) return "";
      return (
        head +
        d.posts
          .map((p, i) => `[${i + 1}/${d.posts.length}] (${p.length} chars)\n${p}`)
          .join("\n\n---\n\n")
      );
    }
    case "advisory": {
      const d = a.advisory;
      if (!d) return "";
      return (
        head +
        `CLASSIFICATION: ${d.classification}\nDISTRIBUTION: ${d.distribution}\nREFERENCE: ${d.reference}\nSUBJECT: ${d.subject}\n\n` +
        d.sections.map((s) => `${s.heading.toUpperCase()}\n${s.body}`).join("\n\n")
      );
    }
    case "infographic": {
      const d = a.infographic;
      if (!d) return "";
      return (
        head +
        `TITLE: ${d.title}\nSUBTITLE: ${d.subtitle}\n\nKEY FIGURES\n` +
        d.stats.map((s) => `- ${s.value} — ${s.label}`).join("\n") +
        `\n\nKEY POINTS\n` +
        d.points.map((p) => `- ${p}`).join("\n") +
        `\n\nFOOTER: ${d.footer}`
      );
    }
    case "execsummary": {
      const d = a.execsummary;
      if (!d) return "";
      return head + `${d.title}\n\n` + d.bullets.map((b) => `• ${b}`).join("\n") + `\n\n${d.body}`;
    }
    case "presentation": {
      const d = a.presentation;
      if (!d) return "";
      return (
        head +
        d.slides
          .map(
            (s, i) =>
              `SLIDE ${i + 1}: ${s.title}\n` +
              s.bullets.map((b) => `  • ${b}`).join("\n") +
              `\n  SPEAKER NOTES: ${s.notes}`,
          )
          .join("\n\n")
      );
    }
    case "report": {
      const d = a.report;
      if (!d) return "";
      return head + `${d.title}\n\n` + d.sections.map((s) => `${s.heading}\n${s.body}`).join("\n\n");
    }
    case "video": {
      const d = a.video;
      if (!d) return "";
      return (
        head +
        `VIDEO PRODUCTION PACKAGE\nLogline: ${d.logline}\nTarget runtime: ${d.runtimeSeconds}s\n\n` +
        `NOTE: This is a production brief. No MP4 is rendered. Actual video generation and analysis of existing video files require a connected video model or production service.\n\n` +
        `STORYBOARD / TIMED SHOT LIST\n` +
        d.shots
          .map(
            (s, i) =>
              `Shot ${i + 1} — ${s.scene} [${srtTime(s.start)} → ${srtTime(s.end)}]\n  VISUAL: ${s.visual}\n  NARRATION: ${s.narration}\n  ON-SCREEN: ${s.onscreen}`,
          )
          .join("\n\n") +
        `\n\nVISUAL DIRECTION\n${d.visualDirection}\n\nPRODUCTION NOTES\n${d.productionNotes}\n\nSUBTITLES (SRT)\n\n${buildSrt(d.shots)}`
      );
    }
  }
}
